version: "3"
services:
  strapi2:
    container_name: strapi2
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapiDB2  
      DATABASE_PORT: ${DATABASE_PORT} 
      DATABASE_NAME: ${DATABASE_NAME} 
      DATABASE_USERNAME: ${DATABASE_USERNAME} 
      DATABASE_PASSWORD: ${DATABASE_PASSWORD} 
      JWT_SECRET: ${JWT_SECRET}  
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET} 
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/usr/src/api/config
      - ./src:/usr/src/api/src
      - ./package.json:/usr/src/api/package.json
      - ./yarn.lock:/usr/src/api/yarn.lock
      - ./.env:/usr/src/api/.env
      - ./public/uploads:/usr/src/api/public/uploads
    ports:
      - "3003:3003"
    networks:
      - strapi2
    depends_on:
      - strapiDB2

  strapiDB2:
    container_name: strapiDB2
    restart: unless-stopped
    env_file: .env
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data2:/var/lib/postgresql/data/
    ports:
      - "5433:5433"
    networks:
      - strapi2

volumes:
  strapi-data2:

networks:
  strapi2:
    name: Strapi2
    driver: bridge
